FROM php:8.2-fpm-alpine

WORKDIR /var/www/application

# php packages
RUN apk add --no-cache \
    curl \
    git \
    build-base \
    zlib-dev \
    oniguruma-dev \
    autoconf \
    bash \
    libzip-dev \
    linux-headers \
    sqlite \
    sqlite-dev \
    && docker-php-ext-install pdo_sqlite

# Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Xdebug
RUN pecl install xdebug && docker-php-ext-enable xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN chown -R www-data:www-data /var/www/application \
    && chmod -R 755 /var/www/application

# port 9000 PHP-FPM
EXPOSE 9000

# run PHP-FPM
CMD ["php-fpm"]
